### ISSUE TITLE
bug: macosx unicode mismatch

### ISSUE THREAD

**Issue by bendemott** [bendemott/solr-zkutil#11]
```
Traceback (most recent call last):
  File "/usr/local/bin/solr-zkutil", line 5, in <module>
    pkg_resources.run_script('solr-zkutil==0.94', 'solr-zkutil')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1357, in run_script
    exec_(script_code, namespace, namespace)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 47, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/solr_zkutil-0.94-py2.7.egg/EGG-INFO/scripts/solr-zkutil", line 13, in <module>
  File "build/bdist.macosx-10.11-intel/egg/solrzkutil/__init__.py", line 871, in main
  File "build/bdist.macosx-10.11-intel/egg/solrzkutil/__init__.py", line 618, in admin_command
TypeError: descriptor 'encode' requires a 'str' object but received a 'unicode'
```

**Comment by bendemott** [comment]
Fixed and tested v0.95
